apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirror-maker
  namespace: kafka2
spec:
  selector:
    matchLabels:
     app: mirror-maker
  replicas: 1
  template:
    metadata:
      labels:
        app: mirror-maker
    spec:
      containers:
      - name: mirror-maker
        image: wpietri/mirror-maker:2
        imagePullPolicy: Always
        env:
        - name: "WHITELIST"
          value: "*"
        - name: "DESTINATION"
          value: "kafka-svc.kafka2.svc.cluster.local:9092"
        - name: "SOURCE"
          value: "kafka-svc.kafka1.svc.cluster.local:9092"