apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
  namespace: prime
spec:
  version: 3.2.0
  connectCluster: "prime"  
  clusters:
  - alias: "netflix"
    bootstrapServers: netflix-kafka-bootstrap:9092
  - alias: "prime" #target
    bootstrapServers: prime-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "netflix"
    targetCluster: "prime"
    topicsPattern: ".*"
    #groupsPattern: "group1|group2|group3"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1